name: Cypress Tests with Mochawesome Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests with Mochawesome
        run: npx cypress run --reporter mochawesome

      - name: Merge Mochawesome Reports
        run: npx mochawesome-merge cypress/reports/*.json -o cypress/reports/mochawesome.json

      - name: Generate HTML Report
        run: npx marge cypress/reports/mochawesome.json -o cypress/reports --reportTitle "Cypress Test Report"

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-html-report
          path: cypress/reports/mochawesome.html
